const CommonRouter = {
    dashboard: '/dashboard',
    master_item: '/master-item',
    mi_create: '/master-item/create',
    mi_edit: '/master-item/item/edit',
    mi_view: '/item/view',
    profile: '/profile',
    company: '/my-company-list',
    company_create: '/company/create',
    company_edit: '/company/edit',
    company_view: '/company/view',
    setting: '/setting',
    channels: "/channels",
    channel_list: "/channels/channel-list",
    channel_connection: "/channel-connection",
    channel_connection_edit: "/channels/channel-connection-edit",
    import_channel_item: "/import-channel-item",
    channel_items: "/channel-items",
    mapped_item: "/mapped-item",
    log_in: '/log-in',
    menu_import_file_log: '/imported-file-log',
    bulk_mapping: '/bulk-mapping',
    master_mapped_items: '/master-mapped-items',
    master_import_data: '/master-import-data',
    orders: '/orders',
    channel_product_mapping: '/channel/product-mapping',
    user_activity_setting: '/setting/user-activity',
    redirect_to_account: `${process.env.LOGIN_DOMAIN}/log-in?product=ecom`
}
export default CommonRouter
