const Header = {
    sr_no: 'SR.NO.',
    company_name: 'COMPANY NAME',
    alias_name: 'ALIAS NAME',
    legal_name: 'LEGAL NAME',
    gst_in: 'GSTIN/UIN',
    gst_applicable_from: 'GST APPLICABLE FROM',
    mobile_no: 'MOBILE NO.',
    email: 'EMAIL',
    registration_type: 'REGISTRATION TYPE',
    party_type: 'PARTY TYPE',
    organization_type: 'ORGANIZATION TYPE',
    industry: 'INDUSTRY',
    pan_it_no: 'PAN/IT NO.',
    address_line1: 'ADDRESS 1',
    address_line2: 'ADDRESS 2',
    pincode: 'PINCODE',
    city: 'CITY',
    state: 'STATE',
    country: 'COUNTRY',
    company_establish_date: 'ESTABLISH DATE',
    subscription_plan: 'SUBSCRIPTION PLAN',
    action: 'ACTIONS',
    product: 'PRODUCT',
    inventory: 'INVENTORY',
    category: 'CATEGORY',
    gst_rate: 'GST RATE(%)',
    status: 'STATUS',
    opening_stock: 'OPENING STOCk',
    channel_name: 'CHANNEL NAME',
    last_connected: 'LAST CONNECTED',
    connection_status: 'CONNECTION STATUS',
    file_name: "FILE NAME",
    success_count: 'SUCCESS COUNT',
    fail_count: 'FAIL COUNT',
    date_and_time: 'DATE & TIME',
    download_file: 'Download File',
    user: 'USER',
    sr: "SR.",
    published_on: "PUBLISHED ON",
    stock_qty: "STOCK QTY",
    stock: "STOCK",
    selling_price: "SELLING PRICE",
    sku: "SKU",
    product_name: "PRODUCT NAME",
    title: "TITLE",
    mrp: "MRP",
    sales_price: "SALES PRICE",
    order_id: 'ORDER ID',
    channel: 'CHANNEL',
    payment: 'PAYMENT',
    order_amt: 'ORDER AMOUNT',
    product_title: "PRODUCT TITLE",
    master_product_name_variant: "MASTER PRODUCT NAME - VARIANT",
    mapped: "MAPPED",
    unmapped: "UNMAPPED",
    activity: 'ACTIVITY',
    module: 'MODULE',
    operation: 'OPERATION',
    channel_type: 'CHANNEL TYPE',
    map_product: 'MAP PRODUCT FROM HERE'
}

export default Header
